# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: HPC Helper 2
author: Prakhar Sharma
copyright: "2025"
logo: assets/HPC_Helper_Logo.png

sphinx:
  config:
    html_theme: pydata_sphinx_theme


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations

# Information about where the book exists on the web
repository:
  url: https://github.com/praksharma/HPC-Helper-2  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
